# -*- coding: utf-8 -*-
"""demo_hugging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgk0sD80kyFKUpy7tOEBZSj3B8dhCdfb
"""

import pandas as pd

from transformers import pipeline
model_path = "cardiffnlp/twitter-xlm-roberta-base-sentiment"
sentiment_task = pipeline("sentiment-analysis", model=model_path, tokenizer=model_path,device=0)
sentiment_task("T'estimo!")

help(pipeline)

base=pd.read_csv('https://github.com/clairett/pytorch-sentiment-classification/raw/master/data/SST2/train.tsv', delimiter='\t', header=None)

base

resultado=base[0][0:10].apply(sentiment_task)

resultado